version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./.:/code
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    expose:
      - "5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"

  web:
    build: .
    command: bash -c "sleep 5; python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000 && python manage.py champions"
#    command: bash -c "python manage.py runserver 0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
