# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('tier', models.CharField(max_length=32)),
                ('queue_type', models.CharField(max_length=64)),
                ('rank', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SummonerLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_points', models.SmallIntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('is_veteran', models.BooleanField()),
                ('is_inactive', models.BooleanField()),
                ('is_fresh_blood', models.BooleanField()),
                ('is_hot_streak', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Account')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.League')),
            ],
        ),
    ]
