# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_league_summonerleague'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='champion',
            new_name='champions',
        ),
    ]
