# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20180131_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='server',
        ),
        migrations.RemoveField(
            model_name='match',
            name='account',
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Account'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Match'),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analytics.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analytics.Region'),
            preserve_default=False,
        ),
    ]
