# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20180222_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='champions',
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='champion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analytics.Champion'),
            preserve_default=False,
        ),
    ]
