# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20180228_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='summoner_level',
            field=models.IntegerField(null=True),
        ),
    ]
