# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_matchplayer_largest_killing_spree'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
    ]
