# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_analyticscache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsCache',
        ),
    ]
