# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_matchplayer_kda'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='kda_perfect',
            field=models.BooleanField(default=False),
        ),
    ]
